version: '3.6'
services:
        elasticsearch:
                image: elasticsearch:8.3.3
                container_name: elasticsearch
                restart: always
                volumes:
                        - elastic_data:/usr/share/elasticsearch/data/
                environment:
                        - node.name=es01
                        - cluster.name=websecaudit-db-cluster
                        - xpack.security.enabled=false
                        - discovery.seed_hosts=es01,es02,es03
                        - cluster.initial_master_nodes=192.168.2.47,192.168.2.89,192.168.2.90,192.168.2.91,192.168.2.92
                        - "ES_JAVA_OPTS=-Xmx4g -Xms4g"
                        - network.publish_host=192.168.2.47
                ports:
                        - '192.168.2.47:9200:9200'
                        - '192.168.2.47:9300:9300'
                networks:
                        - elasticsearch
        kibana:
                image: kibana:8.3.3
                container_name: kibana
                restart: always
                ports:
                        - '192.168.2.47:5601:5601'
                environment:
                        - ELASTICSEARCH_URL=http://elasticsearch:9200
                depends_on:
                        - elasticsearch
                networks:
                        - elasticsearch
volumes:
        elastic_data:
            driver: local
            driver_opts:
              type: none
              o: bind
              device: /mnt/elasticsearch_data
networks:
        elasticsearch:
